apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: kafaka
  labels:
    app: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: crpi-pn2xwedazprppt1j-vpc.cn-beijing.personal.cr.aliyuncs.com/chadong/zookeeper:3.6
          ports:
            - containerPort: 2181
              protocol: TCP
          env:
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"
